### PR TITLE
Make tree only Cylboard when "BETTERCAMERA" is detected

### PR DESCRIPTION
**Pull request by danielh05**
This fixes trees looking weird with the normal sm64 camera.

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
The include is not necessary. Also if you fix that, could you please replace the tabs with spaces to match the rest of the file?

**Comment by danielh05** [comment]
Hopefully that is good enough.

**Comment by fgsfdsfgs** [comment]
Thanks, this should be fine now.

**Comment by coltongit** [comment]
Looking better already. As long as it compiles and works the way it should be.

**Pull request merged**
